version: '3'
services:
  taskflow:
    container_name: taskflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    networks:
      - taskflownetwork
  taskserver:
    container_name: taskserver
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - taskflownetwork
networks:
  taskflownetwork:
    driver: bridge




    